---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users":
    post:
      summary: create a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
              - username
              - password
    get:
      summary: show a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user found
        '422':
          description: not valid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
              required:
              - id
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
